version: '3.8'

services:
  combined-service:
    build:
      context: .
      dockerfile: Dockerfile.combine
    networks:
      - my-network
    ports:
      - "8081:8081"  # Puerto del servicio naturales
      - "8082:8082"  # Puerto del servicio empresas
      - "8080:8080"  # Puerto del servicio cliente

networks:
  my-network:
    driver: bridge
