version: '3'
services:
  empresas:
    build:
      context: ./microservicios/empresas
    ports:
      - "8082:8080"  # Reemplaza el puerto 8080 con el puerto en el que escucha tu aplicación
  naturales:
    build:
      context: ./microservicios/naturales
    ports:
      - "8081:8080"  # Reemplaza el puerto 8080 con el puerto en el que escucha tu aplicación
  cliente:
    build:
      context: ./cliente
    ports:
      - "8080:8080"  # Reemplaza el puerto 8080 con el puerto en el que escucha tu aplicación
