version: '3.8'

services:
  naturales:
    build:
      context: ./microservicios/naturales
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/naturales.jar
    networks:
      - my-network
    ports:
      - "8081:8081"

  empresas:
    build:
      context: ./microservicios/empresas
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/empresas.jar
    networks:
      - my-network
    ports:
      - "8082:8082"

  cliente:
    build:
      context: ./cliente
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/cliente.jar
    networks:
      - my-network
    ports:
      - "8080:8080"

networks:
  my-network:
    driver: bridge
