server.port: 8082
server.error.include-message: always

logging:
  level:
    root: INFO

spring:
  config:
    activate:
      on-profile: "cloud"
  application:
    name: Empresas-Application


---

spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb+srv://carodriguez19:testingtesting123@cluster0.xpofgue.mongodb.net/
      database: Clientes
      auto-index-creation: true

---
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: https://azurearquikeyvault.vault.azure.net/
  config:
    activate:
      on-profile: cloud
  data:
    mongodb:
      uri: ${mongodbConnections}
      database: ${mongoCli}
      auto-index-creation: true
