server.port: 8081
server.error.include-message: always

logging:
  level:
    root: INFO

spring:
  application:
    name: Naturales-Application
management:
  endpoints:
    web:
      exposure: 
        include: health, prometheus
  data:
    mongodb:
      uri: mongodb+srv://carodriguez19:testingtesting123@cluster0.xpofgue.mongodb.net/
      database: Clientes
      auto-index-creation: true